# _config.yml
title: My Awesome Blog
description: Welcome to my awesome blog powered by Jekyll!
theme: jekyll-theme-slate  # 你可以更改为你选择的主题

# _config.yml
title: My Awesome Blog
description: Welcome to my awesome blog powered by Jekyll!
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
